package com.example.firstone.util.recyclerview.Bean;

import com.example.firstone.R;

public class DrinksData {
    public static int[] icon = {
            R.mipmap.drinks_kola,
            R.mipmap.drinks_xuebi,
            R.mipmap.drinks_fenda,
            R.mipmap.drinks_milk,
            R.mipmap.drinks_yogurt,
            R.mipmap.drinks_ad,
            R.mipmap.drinks_ice_red_tea,
            R.mipmap.drinks_molilvcha,
            R.mipmap.drinks_moliqingcha,
            R.mipmap.drinks_red_tea,
            R.mipmap.drinks_green_tea,
            R.mipmap.drinks_puer,
            R.mipmap.drinks_xuanmi,
            R.mipmap.drinks_orange,
            R.mipmap.drinks_taozhi,
            R.mipmap.drinks_apple_juice,
            R.mipmap.drinks_shiliuzhi,
            R.mipmap.drinks_hongzao,
            R.mipmap.drinks_fengmishui,
            R.mipmap.drinks_putaozhi,
            R.mipmap.drinks_youzizhi,
            R.mipmap.drinks_qingningzhi,
            R.mipmap.drinks_xiguazhi,
            R.mipmap.drinks_boluozhi,
            R.mipmap.drinks_xiyouzhi,
            R.mipmap.drinks_wulong,
    };
    public static String[] title = {
            "可乐",
            "雪碧",
            "芬达",
            "牛奶",
            "酸奶",
            "AD钙",
            "冰红茶",
            "茉莉绿茶",
            "茉莉清茶",
            "红茶",
            "绿茶",
            "青柑普洱茶",
            "玄米茶",
            "橙汁",
            "桃汁",
            "苹果汁",
            "石榴汁",
            "红枣茶",
            "蜂蜜水",
            "葡萄汁",
            "柚子汁",
            "青柠汁",
            "西瓜汁",
            "菠萝汁",
            "西柚汁",
            "乌龙茶",
    };
}
